FROM --platform=linux/amd64 node:18
WORKDIR /app

RUN corepack enable
RUN corepack prepare pnpm@7.18.0 --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .
EXPOSE 1337
CMD ["pnpm", "develop"]